### ISSUE TITLE
running cheat on macOS

### ISSUE THREAD

**Issue by Satan-of-heaven** [iqqmuT/civ6-cheat#12]
could someone tell me how I can execute the macOS file? When I call it from the terminal I get the following error: "zsh: no such file or directory" (maybe because the file has no file-ending?)

Thank you for your help!

**Comment by iqqmuT** [comment]
1. Download the file `civ6-cheat-macos` to your Downloads
2. Open up terminal
3. `cd Downloads`
4. Make it executable: `chmod +x ./civ6-cheat-macos`
5. Run it: `./civ6-cheat-macos YourSaveFile.Civ6Save`

You might get an alert from Mac OS about unidentified developer. Then [do this](https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac) and try running it again in the terminal.

**Comment by Satan-of-heaven** [comment]
thank you for your quick help, that worked perfectly! Unfortunately I get stuck on this screen whenever I change any money values (no matter if changing a save game, quick save or autosave); 
![image](https://user-images.githubusercontent.com/19912590/212973975-d521156e-a025-425a-81ff-afb40f74ac4c.png)


have you ever experienced something like this and might know what it's about?

**Comment by iqqmuT** [comment]
Can you post your save file here?

**Comment by Satan-of-heaven** [comment]
Yes of course, here you go: https://filetransfer.io/data-package/xEtx3adr#link

**Comment by iqqmuT** [comment]
Does it get stuck only with modified save files or does it get stuck also when loading your normal save files? In steam community some people are complaining that Mac OS version is getting stuck when loading a save file.... I wonder if this is the same case.

**Comment by Satan-of-heaven** [comment]
I did have that issue they're describing with some saves too, however in that case you get stuck on the earlier loading screen that looks like this:

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/19912590/213800583-8f0ece6a-17f7-4b70-860b-6220935af1d9.png">


and you can't even get to the screen that shows you "your" civilisation. 

I also tried manipulating multiple saves and they all got stuck on the same (not black) loading screen, which only seems to happen to manipulated saves.

**Comment by iqqmuT** [comment]
I can't open your save files with my Linux Civ6 because it is missing the latest mods. I have 1.0.12.9 and you have 1.0.12.28. I tried to run Linux build from the cheat tool against your save file, can you check if that works? https://filetransfer.io/data-package/5XErBH8n#link

**Comment by Satan-of-heaven** [comment]
that worked without issue. Thank you for all your help!  

![SCR-20230122-ris](https://user-images.githubusercontent.com/19912590/213934221-28becb51-42a0-4b41-b4c5-8b5634aa0cfe.jpeg)

**Comment by Satan-of-heaven** [comment]
Could you do me a favour and run the linux build on this save as well? https://filetransfer.io/data-package/JaHw3Eht#link


It's a round 0 save of my favourite settings, that way I can play a couple games with unlimited money. Thank you!

**Comment by iqqmuT** [comment]
I made a new version: v1.3.2. No code changes - just re-packaged it with newer tools. Can you try running that on your local mac? Delete the old version to make sure you are running the new one.

**Comment by Satan-of-heaven** [comment]
works perfectly now, thank you so much!

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/19912590/214136610-44ede0a3-14ff-48b1-a50c-9e93e77b5151.png">
