### ISSUE TITLE
Isn't working

### ISSUE THREAD

**Issue by Tomdngl** [iqqmuT/civ6-cheat#7]
I tried to use in a "vanilla" multiplayer game and the gold don't change in game. The script recognizes the different players, but when you input a new amount, save and load it, just remains the same.

**Comment by iqqmuT** [comment]
Can you try the new release [v1.1.4](https://github.com/iqqmuT/civ6-cheat/releases/tag/v1.1.4)?

If that does not work either, which OS are you using? Or even better yet, can you upload your save file to some cloud service and link it here?

**Comment by Tomdngl** [comment]
Sure, the version of the game is built 1.0.12.9 and I'm using W10. I tried and still not working. Here you got the save file https://drive.google.com/file/d/1SPdNqNgvusDpq6ErRjrJHFpWylJDYbQX/view?usp=sharing
edit: The first time I sent you an edited version of the save. This one is clean.

**Comment by iqqmuT** [comment]
Whoops this issue got auto closed but can you try v1.2.0?

**Comment by Tomdngl** [comment]
You solved it! Now it's working, nice job dude, thanks.
