### ISSUE TITLE
Bitcoin Miner detected

### ISSUE THREAD

**Issue by aPascala** [iqqmuT/civ6-cheat#9]
the actual version cointains a bitcoin-miner.

**Comment by iqqmuT** [comment]
What do you mean?

**Comment by aPascala** [comment]
I checked it. And there´s a bitcoin-miner in the tool.

**Comment by ChrisDKNL** [comment]
https://www.virustotal.com/gui/file/7f0e14055ae9bbe245d057ff70f734653b516281eb49736a79cb07d0d76b89eb
EDIT: use at your own risk

**Comment by iqqmuT** [comment]
Thanks for explaining the situation! I contacted Cylance about this, it must be false positive because everything is open-source and the executable is compiled on Travis CI using `pkg` tool (NodeJS).

**Comment by iqqmuT** [comment]
Apparently Cylance fixed their system and it does not detect bitcoin miner from the executable anymore.

**Comment by FleetAdmiralJakob** [comment]
So, you fixed the miner? Because there are no changes.

**Comment by iqqmuT** [comment]
I haven't made any changes.

If you check the above posted link now, the only negative report is by Zillya (one out of 71). I contacted them to make sure it is not a false positive report but didn't get any response (I kinda understand why when noticed their location).

**Comment by iqqmuT** [comment]
Closing this issue now because VirusTotal does not flag this app as malicious anymore.
